"""
Django settings for cloud_storage project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zk4p5=oe4!y!a10(2pmld1)c^q#t6=+ex3dkd0+5p-@_2gkn@s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storage_app',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cloud_storage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'storage_app.context_processors.stripe_keys',
            ],
        },
    },
]

WSGI_APPLICATION = 'cloud_storage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

if os.environ.get("RENDER") or "PYTHONANYWHERE_DOMAIN" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "render_or_pythonanywhere_db.sqlite3",
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'cloud_db',
            'USER': 'root',
            'PASSWORD': '1994',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Authentication settings
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'  


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







# Backblaze B2 Configuration
AWS_ACCESS_KEY_ID = '0052e2d9a127cc30000000001'  # From B2 dashboard your-key-id
AWS_SECRET_ACCESS_KEY = 'K005FRPgqjGUl0Vm2xlavXjFkdrEFdE'  # From B2 dashboard your-application-key
AWS_STORAGE_BUCKET_NAME = 'cloud-project-vts'  #your-bucket-name
AWS_S3_ENDPOINT_URL = 'https://s3.us-east-005.backblazeb2.com'  # Your region endpoint

# Django Storages settings
DEFAULT_FILE_STORAGE = 'storage_app.storage_backends.BackblazeB2Storage'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'private'
AWS_QUERYSTRING_AUTH = True
AWS_LOCATION = 'media'

# Optional: File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLAOD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB



# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = 'pk_test_51RbOIoR2vlff5nNPNWBXrZWN1vpsZLxrxXRG0MqWANgDycBziueiuDz58csCXEnje39rSsFzzXvc6QaDX2DWmzcb00nONGofBE'
STRIPE_SECRET_KEY = '******REMOVED******_51RbOIoR2vlff5nNPqyouXpWPqkNcfK5POTuHpmheWc1tMZ9NDY5aY9PjSwWJJM7tinsrOdiL0LttRwnQJVFQaytM002a5uU540'


# Plan Configuration
DEFAULT_PLAN = 'free'  # Default plan for new users


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ranjitha13cs@gmail.com'  
EMAIL_HOST_PASSWORD = 'iixy zrjl wzbc vqtk'  
DEFAULT_FROM_EMAIL = 'ranjitha13cs@gmail.com'  

# Email templates configuration
EMAIL_TEMPLATES = {
    'WELCOME': {
        'subject': 'Welcome to Cloud Storage - Your Account is Ready!',
    },
    'SUBSCRIPTION_UPGRADE': {
        'subject': 'Subscription Upgrade Confirmation',
    },
    'SUBSCRIPTION_DOWNGRADE': {
        'subject': 'Subscription Change Notification',
    }
}