# Generated by Django 5.2.3 on 2025-11-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
